# This workflow is designed to ensure that the `dist/` directory in a TypeScript GitHub Action
# is always up-to-date with the transpiled JavaScript code. This is crucial because GitHub Actions
# execute the code found in `dist/index.js`, and any discrepancy between the source TypeScript files
# and this directory could lead to unexpected behavior.
#
# The workflow acts as a Continuous Integration (CI) check for pull requests and pushes to the `main` branch,
# verifying that the `dist/` directory matches the expected output from the source files. If it does not,
# the workflow will fail, indicating that the `dist/` needs to be updated.
name: Check Build

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  # This job runs the build process and checks if the `dist/` directory is up-to-date.
  check-dist:
    name: Check Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access its code.
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      # Setup Node.js using the version specified in `.nvmrc` to ensure consistent environment.
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn

      # Install project dependencies based on the lockfile, ensuring reproducible builds.
      - name: Install Dependencies
        id: yarn-install
        run: yarn

      # Run the build script defined in `package.json` to transpile TypeScript source files
      # into JavaScript in the `dist/` directory.
      - name: Build
        id: yarn-build
        run: yarn build

      # Check if the build process has resulted in any changes to the `dist/` directory
      # that have not been committed. This step ensures that the transpiled code in the repository
      # is always in sync with the source files.
      - name: Compare Directories
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --ignore-space-at-eol --text dist/
            exit 1
          fi

      # This step is conditional and only runs if the previous step fails.
      # It uploads the current state of the `dist/` directory as a workflow artifact,
      # aiding in debugging by allowing you to see what was generated by the build.
      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
